src/browser.rs
src/process.rs
src/web_socket_connection.rs

Here is some code to make the default executable discoverable on multiple platforms. It allows to execute all tests on Linux, which pass (besides the integration tests, which have to go anyway).
`LaunchOptions` inevitably loses the ability to implement `Default`, because we may not be able to (somewhat) safely discover a default path. It is up to the user (and highly platform dependent) what to do then.

WIP Make default executable Platform independen

---

Cargo.toml
tests/form.html
tests/server.rs
tests/simple.html
tests/simple.rs

This adds some basic code to re-add integration tests: We use `tiny_http` to launch a simple http-server and serve static html from there. Tests can easily serve html content and do their worst about it.
Needs expansion.

WIP: Add groundwork for integration tests

---

src/cdtp/dom.rs
tests/simple.rs

This adds a little comfort to handling `Node`

Add Node::find

---

Cargo.toml
README.md
src/lib.rs

This allows testing the code example in `README.md`, at least under nightly as `external_doc` is not stable yet. The current `README.md` did not compile.

Allow README to be doc-tested

---

README.md
examples/real_world.rs
src/lib.rs

These were originally my "integration tests", but they're too network-dependent and flaky for that. I had deleted them, but they're probably worth keeping in `examples/` for now as a source of documentation.

Add "real world" examples

---

Cargo.toml
README.md
src/lib.rs

The `termcolor`-crate should be unneeded (and is in fact); if downstream wants colored output, they can always do that.
README has been broken by recent changes

Two small fixes

---

src/cdtp/dom.rs

closes: #18 
closes: #19 
If it's possible to implement that custom deserialize without an explicit clone on the values I wasn't able to do it. I get a 'cannot move out of borrowed content' borrowck error if I don't clone. Any ideas?
Something I learned: when you do custom deserialize for Option values you need `#[serde(default, ... )]` otherwise serde will panic. I tested this out on a few pages to make sure it could print node attributes properly.

Convert NodeAttributes to Map, add Node fields

---

Cargo.toml
README.md
examples/real_world.rs
src/browser/mod.rs
src/browser/process.rs
src/lib.rs
tests/simple.rs

Using the builder pattern means that the auto detection function will only run if the path was not specified.

Use the builder pattern for launch options

---

examples/query_wikipedia.rs

A free-standing version of whats in `real_world.rs`.
I noticed that `tab.wait_for_element()` and especially `tab.find_element()` can return an error `NoElementFound` that is no longer public and therefor can't be matched against. We currently can't distinguish if the element is simply not there or if the browser failed in some other way.

Add query_wikipedia example

---

examples/take_screenshot.rs
src/browser/tab/mod.rs
src/cdtp/page.rs
tests/simple.rs

This fixes the test being broken on MacOS for some reason (the screenshot taken from the view is just 1x1 pixel), improves the API (no optional parameters that sometimes get ignored, sometimes not) and adds an executable example.

Improve screenshot API, add example

---

src/browser/mod.rs
src/browser/tab/mod.rs
src/browser/transport/mod.rs

Feel like there's a nicer way to do this with traits and generics, but it's a little too late at night for that, and I'm pretty sure this is an improvement.

DRY up the two call method methods

---

examples/take_screenshot.rs
src/browser/tab/element.rs
src/browser/tab/mod.rs
src/cdtp/page.rs
tests/simple.html
tests/simple.rs

Here is an implementation of the `clip` argument on `captureScreenshot`, which allows taking a screenshot of specific regions on the page. The functionality has been hotwired to `tab::Element` so one can do `tab.wait_for_element("div#foobar")?.capture_screenshot(ScreenshotFormat::PNG)?` to get a screenshot of that specific element. See `capture_screenshot_element_box()` for how to do this in a more fine-grained way. Docs, tests and examples were expanded.
Two problems remain:
* `tab::Element` is not public and so it's not documented, neither are `BoxModel`, `ElementQuad` etc. This is the same problem as with `NoElementFound` returned by `tab.find_element()`.
* The integration tests all fail in mysterious and flaky ways. Most of the time they just time out, sometimes `transport` complains …

WIP: Implement clip on captureScreenshot

---

.travis.yml
src/browser/mod.rs
src/browser/process.rs
src/browser/tab/element.rs
src/browser/tab/mod.rs
src/browser/tab/point.rs
src/browser/transport/mod.rs
src/browser/transport/web_socket_connection.rs
src/cdtp/mod.rs
src/lib.rs

```rust
#![deny(clippy::pedantic)]
#![allow(
clippy::stutter,
clippy::doc_markdown, // a number of false positives here
clippy::default_trait_access, // fails on output of derive_builder
clippy::needless_pass_by_value // would stop us creating and passing in LaunchOptions to browser in one statement
)]
```
Fixes #72

Enable most of clippy::pedantic by default

---

src/browser/process.rs

We could actually error-out if extensions are given and headless in true - this simply will not work.

Add note about extensions while headless

---

src/browser/tab/element.rs
tests/simple.html
tests/simple.rs

Some helper functions on `BoxModel` that are handy when writing tests downstream, to check simple geometry (e.g. "is this element roughtly where it's supposed to be")

Add BoxModel-helpers

---

src/browser/tab/mod.rs
src/protocol/mod.rs
src/protocol/profiler.rs
tests/coverage.rs
tests/coverage_fixtures/basic_page_with_js_scripts.html
tests/coverage_fixtures/coverage_fixture1.js
tests/coverage_fixtures/coverage_fixture2.js
tests/server.rs

Unlike Puppeteer (and related to this comment: https://github.com/atroche/rust-headless-chrome/issues/82#issuecomment-470167972) I'm not munging the data from Chrome into a friendlier format. We can always add helpers for that later if this causes confusion (or make it the default, to keep more in line with Puppeteer's API as opposed to the Chrome DevTools API).
The test is probably the best entry point for reading this PR, although on the whole I'm doing little more than wrapping raw CDTP methods.

Add wrappers for starting, stopping and taking JS coverage

---

src/browser/tab/element.rs
tests/simple.rs

This adds more helper functions to `ElementQuad` that I'm using in tests to the tune of `assert!(foo_node.content.within_horizontal_bounds_of(&bar_node.margin))`

Add more helper-methods on ElementQuad

---

src/browser/tab/element.rs
src/browser/tab/mod.rs
src/browser/transport/mod.rs
src/protocol/dom.rs
src/util.rs
tests/simple.rs

Still unsure about the whole `wait` vs `find` part of the API, and also the necessity of the "custom timeout" version, and also the `found_via_selector` field, but those can wait for another time.

Add find / wait for elements methods

---

tests/simple.rs

I still don't know why there are subtle color differences in the screenshots, it should be pixel perfect. This should silence CI.

Make screenshot tests more resilient

---

.travis.yml
Cargo.toml
README.md
src/browser/fetcher.rs
src/browser/mod.rs
src/browser/process.rs
src/browser/tab/mod.rs

I killed the progressbar and removed `indicatif`
`reqwest`, `zip`, and `directories` are optional, but default. so @lukaslueg you should be fine to run w/o bringing in any tokio deps by using:
```
[dependencies.headless_chrome]
default-features = false
``` 
Come to think of it, I need to add that to the readme

Add fetcher as a default feature

---

Cargo.toml
src/browser/fetcher.rs

#93 let's close this
This came up a few times; reqwest brings in a huge transitive dependency. It was suggested to replace with `ureq`. It looks cross platform? I don't have any environments other than linux to test.
If someone could try on mac & windows that'd be nice.
Also, prints DL size in MiB now instead of bytes

Replace reqwest with ureq

---

src/browser/mod.rs
src/browser/process.rs

This adds the `--window-size` option to the argument list. [Two](https://travis-ci.com/iwatakeshi/rust-headless-chrome/builds/109332816) of the Travis builds [are failing](https://travis-ci.com/iwatakeshi/rust-headless-chrome/jobs/195028831#L733) but it seems irrelevant to the changes I made. If this is something I need to take care of, please let me know.

Add window size option

---

src/browser/process.rs

This adds the `--no-sandbox` option. While it's not wise to use this option, there are times where it's needed such as using chrome in a docker container. By default, sandbox is enabled so the behavior is the same as before.

Add sandbox option

---

src/browser/mod.rs

This adds additional paths to `default_executable()`. It also adds a check for an environment variable that may contain a path to the executable. 
I wasn't sure if `$CHROME` would be a good variable. I thought `$BROWSER` was too generic and may imply that Firefox or another browser can be accepted. If you like me to change it to `$BROWSER`, please let me know. Thanks.

Add chrome paths

---

.travis.yml
src/lib.rs

This should hopefully fix the CI builds of the project.
[This](https://changelog.travis-ci.com/ubuntu-xenial-16-04-build-environment-update-86123) is the breaking change in Travis CI which affected this project 5 months ago.

Fix Travic CI

---

src/browser/tab/element.rs
src/browser/tab/mod.rs
src/util.rs
tests/simple.rs

There is an odd issue with `wait_for_element` and `wait_for_elements` methods:
If an unexpected error occurs while you wait for some element (for example the browser gets closed / killed) you would expect that the blocking call to `wait_for_element` will fail immediately and provide a meaningful error (for example `RemoteError { code: -32602, message: "No session with given id" }`).
Instead what happens is that you keep on waiting for your call to finish and when it finally does - you get the standard `Timeout` error so you can't respond to the actual problem at hand.
This PR addresses the issue above, by implementing a stricter until method that can explicitly allow certain errors while failing and reporting the rest.

Fix stalled wait-for-element calls

---

src/browser/mod.rs
src/browser/tab/mod.rs
src/browser/transport/mod.rs
src/protocol/mod.rs
src/protocol/network.rs
tests/simple.rs

Adds a `Tab::enable_response_handler` method that installs a callback that will be called for each finished network request.
The callback receives the response info, and also a additional method that retrieves the payload. (I'm not so sure about that one, but I think it's the most straight-forward solution)
A test is included. 
Closes #132

Add response handling callback for tabs.

---

.travis.yml
Cargo.toml

Removing the `default_features` for `failure` removed the `derive` feature, which sneaked back in if `headless_chrome` was compiled with default features enabled. Current master and `0.4.0` will not compile for `cargo check --no-default-features` or as a dependency `rust_headless_chrome = { version = "0.4", default_features = false}`. This went unnoticed because CI does not test with `--no-default-features`.
This re-introduces the default features on `failure` and introduces extra testing for CI. The currently release `0.4` should be yanked and `0.4.1` released.

Fix missing failure-feature

---

src/browser/tab/mod.rs
tests/coverage.rs
tests/logs.rs
tests/simple.rs

Fixes https://github.com/atroche/rust-headless-chrome/issues/146 and should help with https://github.com/atroche/rust-headless-chrome/issues/153

Re-enable and fix response handling test, add docstring which warns of limitations

---

src/browser/tab/mod.rs

Quality of life improvement PR.
Instead of writing everywhere:
```rust
wait_for_element_with_custom_timeout(selector, std::time::Duration::from_secs(5));
wait_for_element_with_custom_timeout(selector1, std::time::Duration::from_secs(5));
...
```
(which is a bit verbose)
We can now write:
```rust
tab.set_default_timeout(std::time::Duration::from_secs(5))
wait_for_element(selector);
wait_for_element(selector1);
```
It also allows `wait_for_elements` timeout to be changed, prior to this, only `wait_for_element` timeout was configurable

Add a default_timeout for Tab

---

src/browser/process.rs

See: 
https://github.com/atroche/rust-headless-chrome/issues/127
https://github.com/GoogleChrome/puppeteer/blob/master/lib/Launcher.js#L38

Run Chrome with same 'DEFAULT_ARGS' as puppeteer (Fixes #127)

---

CHANGELOG.md
Cargo.toml
README.md

I think it's a bit dangerous having it as a default when we're not testing it on CI, and when we're not regularly using it ourselves. There are probably more issues like this lurking: https://github.com/atroche/rust-headless-chrome/issues/143

Remove fetch as default feature

---

src/browser/tab/mod.rs
src/protocol/mod.rs
src/protocol/page.rs
src/protocol/runtime.rs
src/protocol/target.rs
tests/events_fixtures/events_page.html
tests/events_listeners.rs

Adds `Runtime.enable` and `Runtime.disable` methods, so you can receive `runtime` events.
Adds event listener to listen to the events (see `tests/events_listeners.rs` for more details). 
Relates #106

Improve Runtime Domain, Add EventListeners callbacks.

---

CHANGELOG.md
examples/query_wikipedia.rs
examples/take_screenshot.rs
src/browser/mod.rs
src/browser/process.rs
src/browser/tab/element/mod.rs
src/browser/tab/mod.rs
src/lib.rs
src/protocol/dom.rs
tests/extension.rs

Useful (for me!) at least until this gets solved: https://www.bountysource.com/issues/49744518-add-generated-structs-as-autocomplete-suggestions

Easier access to launch options builder

---

src/browser/mod.rs
src/browser/tab/mod.rs
src/protocol/page.rs
src/protocol/target.rs
tests/simple.rs

Add next functionality to tabs:
1. `Tab#close_target`  - closes the tab.
2. `Tab#close_with_unload` - tries to close the tab, but emits `beforeunload` event.
3. `Tab#close(boolean)` - helper function that chooses one of the functions above depending on the boolean parameter.
4. `Tab#activate` - activates current tab (makes it focus).

Tabs additional functions

---

Cargo.toml

The performance of `zip-rs` has historically not been that great, they switched recently to flate2 away from libflate, and it's been improved [a lot](https://github.com/mvdnes/zip-rs/pull/107). This PR just provides a min version number for `zip-rs`.
FYI, when the current master is run, it doesn't appear to download anything. It looks like there's another PR (#182) that gets everything working again, so I didn't spend much time with it.

Give min version for zip (increase zip performance)

---

src/protocol/dom.rs
tests/shadow-dom.html
tests/simple.rs

Elements with `closed` attached shadow DOM elements currently fail to parse when you `wait_for_element`. This PR changes the `ShadowRootType` enum to match allowable shadow root modes: https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot/mode

Match ShadowRootType enum with ShadowRoot modes

---

examples/settings_and_event.rs
src/browser/process.rs
src/browser/tab/element/mod.rs
src/browser/tab/mod.rs
src/util.rs
tests/events_listeners.rs

https://github.com/atroche/rust-headless-chrome/commit/a93a0e2ac89da641ad73850115459bc8e22e8789 - i made LaunchOptions public and added access of tab in event closure
https://github.com/atroche/rust-headless-chrome/commit/a14d61d48a53912b0a66bafff5ca831c238fb66c - on low speed networks sometimes the dom renders very late, because of this it cant find midpoints to click on the element. so i added functionality to extract midpoints after failure.

Make LaunchOptions customizable and enable extracting midpoints after failure

---

examples/query_wikipedia.rs
examples/take_screenshot.rs

Update the examples to use LaunchOptionsBuilder instead of LaunchOptions in the Browser constructor.
As discussed in issue #203

LaunchOptionsBuilder in examples

---

src/browser/mod.rs

This is a follow-up for issue #142, extending the solution provided in PR #145.

Make a connect variant which accepts idle_browser_timeout

---

src/protocol/dom.rs

Added the css ::marker pseudo element that resulted tab.find_element() to panic when it present in the html.

added css marker pseudo element

---

src/browser/process.rs

This is helpful for performing tests/executions that rely on data stored in the user directory.
**Usage:**
```
let browser = Browser::new(
LaunchOptions::default_builder()
.user_data_dir(Some(PathBuf::from("./rust-headless-chrome-profile")))
.build()
.expect("Could not find chrome-executable"),
)?;
```

Add ability to specify a user data directory (profile)

---

src/browser/tab/mod.rs
src/protocol/network.rs
tests/simple.rs

Support setCookies #5
I implemented some methods the same as GetCookies.
https://chromedevtools.github.io/devtools-protocol/tot/Network/#type-CookieParam
https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-setCookie
https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-setCookies
https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-deleteCookies
Tab::{set_cookies, delete_cookies} use them with the url opened in tab, just like puppeter.
Please review.

Support setCookies #5

---

examples/call_js_function_with_args.rs
examples/settings_and_event.rs
tests/expose_function.rs

This PR removes some unused imports and prefixes an unused variable with an underscore. Purpose of these changes is to get rid of the associated compiler warnings.

Remove unused imports to pass clippy tests

---

src/browser/mod.rs
src/browser/process.rs
src/browser/tab/element/mod.rs
src/browser/tab/mod.rs
src/browser/transport/mod.rs
src/protocol/dom.rs
src/protocol/fetch.rs
src/protocol/mod.rs
src/protocol/network.rs
tests/simple.rs

Added the ability to include command line args.
Example: LaunchOptionsBuilder::default().args(vec!["--proxy-server=127.0.0.1:8888"])
Added Fetch domain, with methods: enable_fetch(), disable_fetch(), enable_request_interception(), authenticate()
Added network::SetExtraHttpHeaders protocol and set_extra_http_headers()
Added network::SetCookies protocol and set_cookies() method

LaunchOptions, Fetch Domain, authenticate()

---

src/browser/tab/mod.rs

This PR removes an unresolvable import that prevents the latest master from building:
```
error[E0432]: unresolved import `serde::__private`
--> src/browser/tab/mod.rs:12:12
|
12 | use serde::__private::ser;
|            ^^^^^^^^^ could not find `__private` in `serde`
```
It also removes those two unused imports:
```
warning: unused import: `Deserialize`
--> src/browser/tab/mod.rs:14:13
|
14 | use serde::{Deserialize, Serialize};
|             ^^^^^^^^^^^
|
= note: `#[warn(unused_imports)]` on by default
warning: unused import: `CookieParam`
--> src/browser/tab/mod.rs:35:40
|
35 | use crate::protocol::network::{Cookie, CookieParam};
|                                        ^^^^^^^^^^^
```

Fix broken imports

---

src/browser/tab/mod.rs
src/protocol/dom.rs
src/protocol/page.rs
tests/simple.rs
tests/transparent.html

From Chrome API: 
https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setDefaultBackgroundColorOverride
I propose the integration of two functions: 
- set_transparent_background_color
- set_background_color
I find this very useful when you use chrome headless for some rendering in png. 
This feature of transparency exist with Puppeteer (know as the option : 'omitBackground', when you take a capture). 
Doc:

Feat set background color

---

src/browser/mod.rs
src/browser/tab/element/mod.rs
src/protocol/css.rs
src/protocol/mod.rs
tests/simple.rs

Implemented method `get_computed_styles' on the Element struct which returns array of CSS styles.

Feat: add method to get CSS styles from element

---

src/browser/process.rs

See https://github.com/atroche/rust-headless-chrome/issues/261 for details and steps to reproduce.
It appears that a regular expression used to detect problems with binding devtools websocket actually matched some other unrelated messages like:
```
[0703/145506.975691:ERROR:address_tracker_linux.cc(214)] Could not bind NETLINK socket: Permission denied (13)
```
This message seems to be releated to some other socket, not the devtools one.
The fix is to make regular expression matching these message a bit more specific.

Fix DebugPortInUse error when running inside gVisor

---

src/browser/process.rs

The logic to enable the option was invalid.

fix ignore_certificate_errors flag, idle_browser_timeout, process stderr handle

---

src/browser/mod.rs
src/browser/process.rs

Adds a parameter to the LaunchOptionsBuilder, which disables the default arguments and makes the default arguments public.

Add parameter to disable default arguments

---

src/browser/fetcher.rs
src/browser/mod.rs
src/browser/process.rs
src/browser/transport/mod.rs
src/lib.rs

Closes #291 
Also fixes the fetcher module (feature = "fetch"), as `failure` doesn't seem to be used anymore + a few other problem that came up.

Browser sync

---

src/browser/tab/mod.rs
tests/simple.rs

In addition to `type`, puppeteer also has this method for text input: [`sendCharacter`](https://github.com/puppeteer/puppeteer/blob/ce0dd25349b3141409cf68121a2bf9a770d9ecf7/src/common/Input.ts#L243)
What this does is it just passes the provided input text to the `Input::InsertText` method without any processing. This is very useful because when we have a lot of text, the normal `type` (or `type_str` in our case) method takes a very long time. The `sendCharacter` method does it instantly.
1. Created the `send_character` method.
2. Changed `type_str` so now it uses the new `send_character` method instead of calling `Input::InsertText` directly. No real reason for this change, but I think it makes the code a little more organized.
<br>
_Note: I'm not very happy with neither the method name …

Created `send_character` method as a much faster alternative to `type_str`

---

src/browser/process.rs

Currently it seems that the chrome profiles that are automatically created when spawning a browser without specifying the user_data_dir are not deleted, resulting in high disk space usage.
The bug seems to happen because the instance of `tempfile::TempDir`, which handles deletion of the directory upon drop, is not kept around after the browser is launched (see https://docs.rs/tempfile/latest/tempfile/struct.TempDir.html#resource-leaking).
This should fix the issue, reported here:
https://github.com/atroche/rust-headless-chrome/issues/311
I'm not very happy about the (minimal) use of `unsafe` code in the test code and I'm open to suggestions.
I opted for the dirty global static solution for testing because I did not want to alter the lib's API and expose that temporary path too high up, …

Automatically delete temporary user_data_dir when none was explicitly provided by the user

---

src/browser/tab/element/mod.rs
src/browser/tab/mod.rs
tests/simple.rs

Adds two new methods for get the full HTML contents of a tab or a selected element.
The String returned by `tab.get_content()` can be parsed by [scraper](https://crates.io/crates/scraper) with the method `scraper::Html::parse_document`. 
The String returned by `elem.get_content()` can be parsed by [scraper](https://crates.io/crates/scraper) with the method `scraper::Html::parse_fragment`.
The way it gets the HTML is by running a JS function. I don't know if this is the best way to do it, but I can't think of any other way.

Created methods to get full HTML from page and elements

---

src/browser/mod.rs

Added another entry for microsoft edge to autodetect with.
The binary name for msedge on some OS's (some linux distros namely such as Silverblue) is `microsoft-edge`.

Added `microsoft-edge` to list of bins to look for

---

Cargo.toml

If any downstream crates are using rustls, they will potentially have issues since the current `auto_generate_cdp/reqwest` dependency uses the `native-tls` default feature. This change would allow for this to be toggled.
Requires https://github.com/mdrokz/auto_generate_cdp/pull/2 to be merged.
Signed-off-by: Sean Pianka <pianka@eml.cc>

build: Add feature for enabling rustls in deps

---

src/browser/tab/mod.rs
tests/coverage_fixtures/basic_page_with_loading_failed_element.html
tests/simple.rs

It was developed according to the format of the `register_response_handling` method.

Add networkLoadingFailed handler

---

src/browser/mod.rs
src/browser/tab/mod.rs
src/browser/transport/mod.rs
tests/simple.rs

I got a panic when passing `expression` with multi-byte characters to `browser::tab::Tab::evaluate`.
I found out the problem is wrong usage of `String::truncate`, so this PR replaces these usages to safer method.
e.g.
```rs
// this is fine.
String::from("abcde").truncate(1);
// this panics because character '★' is 2-bytes long, and we can't split it halfway.
String::from("★★★").truncate(1);
```

Fix usage of String::truncate

---

Cargo.toml
src/browser/mod.rs
src/browser/process.rs
src/browser/transport/mod.rs
src/browser/transport/web_socket_connection.rs
tests/simple.rs

As requested in https://github.com/atroche/rust-headless-chrome/pull/349#issuecomment-1366959108.
the difference between this pr and the referenced pr is that this uses `tungstenite` directly instead of `tokio-tungstenite` so this doesn't pull in async runtime. 
Unlike `websocket` and `tokio-tungstenite`, `tungstenite` doesn't provide split API and mutable reference to WebSocket is required to send and receive messages, so mutex is used. `TcpStream::set_read_timeout` is used to avoid the receiver thread locking the mutex for too long.
This fixes https://github.com/atroche/rust-headless-chrome/issues/322.

migrate websocket to tungstenite

---

src/browser/tab/mod.rs

**Problem**
If you run tab.find_elements_by_xpath(..), tab.wait_for_elements_by_xpath() as first commands in your file, they won't work.
**Solution**
Add a call to get_document() in find_elements_by_xpath(..) function, in the same way as find_elements(..) already does.

call get_document() in find_elements_by_xpath

---

src/browser/fetcher.rs
src/browser/mod.rs
src/browser/process.rs
src/browser/tab/mod.rs
src/testing_utils/logging.rs
src/testing_utils/server.rs
src/types.rs

Increased use of `?` over `unwrap`.

Handle more `.unwrap()`'s

---

src/browser/fetcher.rs
src/browser/process.rs

Small improvement to add derive(Debug) to 2 structs and adding tracing logging for the CLI options used to start the headless browser.
With the old version I had the issue of `print_to_pdf` always working sequentially even though I used it with futures and I was trying to make multiple PDF at the same time. Will test if this issue has persisted.

Add derive(Debug) and tracing logging

---

src/browser/fetcher.rs

1. fetch revision 1095492 is the same as the current [chrome revision of puppeteer](https://github.com/puppeteer/puppeteer/blob/b14628738010ab80960a1834c2db85bbe1223bac/packages/puppeteer-core/src/revisions.ts#L21).
2. Added a dependency to install the Chrome browser on Arm-based macOS.

Updated Chrome revision and added Mac_Arm chrome installation

---

src/browser/tab/element/mod.rs

Generally, we want to access an Element attributes and basic props when we create it, so why calling `get_attributes()` when we can already cache useful dom information, during the same Element instantation? I found out that it is literally a zero cost operation.
**Also**
- `get_attributes()` calls `get_description()` which has a depth of 100
- From my experiments, on long and complex pages it saves a lot of overhead (even couple of seconds per page)
_Open point for another time_
- Why do `el.get_description()` and `tab.describe_node()` have a depth of 100? Maybe we can parametrize it

Cache Attributes, Tag Name and Value on Element creation

---

src/browser/fetcher.rs
src/browser/mod.rs
src/lib.rs

Fixed fetcher as discussed in 
https://github.com/rust-headless-chrome/rust-headless-chrome/pull/374#discussion_r1112055894 and https://github.com/rust-headless-chrome/rust-headless-chrome/pull/374#issuecomment-1435509578
Now Revision::Latest gets the revision and installs the latest version of Chrome on that platform.
e.g
```rust
// let revision = headless_chrome::Revision::Specific("634997".into());
let revision = headless_chrome::Revision::Latest;
let fetcher_options = headless_chrome::FetcherOptions::default()
.with_revision(revision);
let launch_options = headless_chrome::LaunchOptionsBuilder::default()
.fetcher_options(fetcher_options)
.build()?;
let browser = Browser::new(launch_options)?;
```

Added installation latest version of chrome and refactored fetcher

---

src/browser/process.rs

Resolve https://github.com/rust-headless-chrome/rust-headless-chrome/issues/371 according to the idea from @vootooguru and verification from @ameleumit
I add `enable_logging` to LaunchOptions and make it disabled by default.

Make `--enable-logging` not hard coded

---

src/browser/tab/element/mod.rs

This is in response to [#364](https://github.com/rust-headless-chrome/rust-headless-chrome/issues/364)
to get a better error in the case we try to click on an element which is hidden / not visible.

better error for click on element which is not visible

---

src/browser/tab/element/mod.rs

Seemingly a quintessential function for an Element object, and there is indeed [people asking for it](https://github.com/rust-headless-chrome/rust-headless-chrome/issues/308), and [chromiumoxide implements it](https://github.com/mattsse/chromiumoxide/blob/939a12664ac6fc85fde92112f80bcafdb3e26421/src/element.rs#L334).

Add get_attribute_value() for Element

---

src/browser/process.rs
src/browser/tab/element/mod.rs

It seems sometimes after finding an element, if immediately calling something like `.click()`, we get a panic at unwrapping a `None`. The related code seems to assume this should never happen. Maybe it's a better idea to propagate the error upward.

Propagate error of unable to find midpoint upward instead of panicking

---

src/browser/tab/mod.rs

Identical to `press_key`, but with an optional u32 bitfield which can be constructed from a slice of `ModifierKey` elements to specify which modifiers could should be held down (forwarded directly to the `modifiers` parameter of the [`Input.dispatchKeyEvent`](https://chromedevtools.github.io/devtools-protocol/tot/Input/#method-dispatchKeyEvent).

Add `press_key_with_modifiers`

---

src/browser/process.rs

When running as root the error reported is misleading:
```
There are no available ports between 8000 and 9000 for debugging
```
This commit fixes this and reports the proper (new) error `RunningAsRootWithoutNoSandbox`:
```
You need to set the sandbox(false) option when running as root
```

Fixes wrong error message when running as root in sandbox mode

---

.github/workflows/ci.yml
Cargo.toml
src/browser/fetcher.rs

Currently `rust-headless-chrome` developers mainly develop on Linux systems or don't have Windows systems to test on. Moreover the Github actions also don't run tests for the Windows platform.
Therefore `rust-headless-chrome` may release broken crates that affect Windows or MacOS systems and the bugs might go unnoticed for a release or two.
Such as happend recently in https://github.com/rust-headless-chrome/rust-headless-chrome/issues/427 or https://github.com/mdrokz/auto_generate_cdp/issues/12 And even when patching those it was hard to get the patch right, even when the build didn't even pass a simple compile.
This pull request ads `windows-latest` to `ci.yml`. This will increase build-minutes, but make it immediately obvious if there is a problem building `rust-headless-chrome` for …

ci.yml Also run tests on windows-latest and macos-latest and fix platform specific build errors and warnings

---

src/browser/tab/element/mod.rs
src/browser/tab/mod.rs
src/browser/transport/web_socket_connection.rs

Resolves #436
This was added in #386, but somehow it gets replaced with default value again.

use max frame size and message size for web socket connections

---

Cargo.toml

Enable the `proxy-from-env` feature in `ureq` for the optional `fetch` feature so that chrome-headless can be downloaded via system proxy.

chore: enable ureq proxy-from-env

---

src/browser/mod.rs

We should attempt to close gracefully before killing the process.

Call Browser.Close on drop

---

src/browser/tab/mod.rs

Just a small docs change that links to this file:
https://github.com/puppeteer/puppeteer/blob/62da2366c65b335751896afbb0206f23c61436f1/lib/USKeyboardLayout.js
which seems like it defines the various strings and their keys

[docs] Add links for `Tab.press_key`

---

src/browser/process.rs

removed audio disable argument in order to play audio in chrome

removed audio disable argument

---

README.md

Those were doc comments instead of regular comments, so the compiler gives a bunch of warnings when you copy paste the example to try it out because there's nothing to document.
Edit: fixed the broken `LaunchOptionsBuilder` links too

Readme fixes (use regular comments + fixed some links)

---

README.md

Corrected the damage to the build status badge caused by a project address change.

docs: :memo: fix ci status badge

---

Cargo.toml

It will be helpful for the down stream crates to know what the minimum supported Rust version (MSRV) for their dependencies so they can decide how to bump their version and when, because it's considered as a breaking change

chore(msrv): set to 1.70

---

README.md

Hi!
Small docs-only change that explicitly shows that you can simply save the screenshot to disc  using `std::fs::write("screenshot.jpeg", jpeg_data)?;`, it wasn't immediately obvious to me that I could just write the bytes to disc.

Save screenshots to disc in README.md

---

Cargo.toml

Updated cargo dependencies and rust version.
Fixes https://github.com/rust-headless-chrome/rust-headless-chrome/issues/485

Updated cargo dependencies

---

Cargo.toml

I compiled the crate and found a warning complaining about an obsolete use of `deafult_features`:
```
warning: `default_features` is deprecated in favor of `default-features` and will not work in the 2024 edition
(in the `chrono` dependency)
warning: `default_features` is deprecated in favor of `default-features` and will not work in the 2024 edition
(in the `jpeg-decoder` dependency)
```
so I fixed it.

Replace deprecated `default_features` with `default-features`

---

src/browser/tab/mod.rs

The `trace!` output of `Tab::call_method` was trying to print the first 70 characters of the result of the method call, but it was printing an iterator instead.  As a result, it print much more long log even than the original string despite the intention.  I fixed the bug.

Bugfix: iterator instead of string was printed

---

src/browser/mod.rs
src/browser/process.rs
src/util.rs

- Fix: when having a `add_event_listener` and `headless=false` and `devtools` is open (manually opened or via arguments), it will crash due to the error: `got TargetInfoChanged event about a tab not in our list`. Chromium opens a new tab and triggers: Event TargetCreated type=‘other’ with empty url field. Next the Event::TargetInfoChanged and the tab with type other does not exists in our tracked tabs list.
- Add: launcher option `devtools`, it forces headless to be `false`. Make sure its the same behaviour as Puppeteer.
@ maintainers: Do we want to track devtools tabs? Currently I skip the devtool tabs to be tracked.

Added devtools to launch options

---

src/browser/process.rs
src/util.rs

Implemented launch option `ignore_default_args` same as what Puppeteer has implemented.
This is useful for excluding default arguments, such as ignoring: `--enable-automation`
For example: [puppeteer/docs/troubleshooting.md at main · puppeteer/puppeteer](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#chrome-doesnt-launch-on-windows)

add `ignore_default_args` to launch options

---

src/browser/process.rs

See https://github.com/rust-headless-chrome/rust-headless-chrome/issues/500 for more information.
Successfully merging this will close #500.

[Fix] Fix mismatched default value in `LaunchOptions`

---

src/browser/mod.rs

It is useful to launch chrome directly with `<url>` (or `--app=<url>`) as argument, if you use headful browser.
Not opening empty tab is essential for [simple neovim plugin](https://github.com/dimchee/prochrome.nvim) I am developing. 
It would be nice too if `--app=<url>` option was part of `LaunchOptions`.
I have seen that others had same issue as me, so this fixes #392.

Disable automatic tab creation on launching chrome

---

src/browser/mod.rs

Sometimes we need to deploy webdriver separately, so added a method to expose the deployment address.

Add get_ws_url to expose ws url

---

src/browser/fetcher.rs

Use `info!` instead of `println` if needed

chore: remove unnecessary println

---

src/browser/mod.rs

While automating Google account sign-in, a new popup ask for to confirm the account link with the browser. However, this popup is unhandled and lead the software to panic. This will fix the crash by redirecting the error as unhandled.

Fix for Google Chrome sign-in
