- .gitignore
- src/element.rs
- src/tab.rs
Some fixes for issue #14 
Some housekeeping on gitignore as well
> Allow methods to be chained

- src/process.rs
- src/transport.rs
- src/waiting_call_registry.rs
- tests/simple.rs
> Handle browser / WS conn being closed while using tab 

- src/browser.rs
Still plenty more needed, but this should help.
> Add Struct-level docs to Browser

- src/cdtp/page.rs
- src/tab.rs
- tests/server.rs
- tests/simple.rs
The effect of `scriptToEvaluateOnLoad` is unclear to me, I could not get it to do anything...
> Implement reload

- Cargo.toml
- src/cdtp/page.rs
- src/tab.rs
- tests/simple.html
- tests/simple.rs
Here is an implementation to take screenshots from the current page
> Implement captureScreenshot

- src/browser/mod.rs
> Add new_tab method to browser

- .travis.yml
- examples/take_screenshot.rs
- src/browser/mod.rs
- src/browser/process.rs
- src/browser/tab/mod.rs
- src/browser/transport/mod.rs
- src/browser/transport/waiting_call_registry.rs
- src/browser/transport/web_socket_connection.rs
- src/cdtp/mod.rs
- tests/simple.rs
Seems like tests haven't actually been running 🤦‍♂️
> Run cargo test on CI (Linux / Mac only)

- src/browser/tab/element.rs
- src/cdtp/dom.rs
- tests/simple.html
- tests/simple.rs
Fixes #63 
The next step is to hotwire this to `capture_screenshot`
> Implement DOM.getBoxModel

- src/browser/mod.rs
- src/browser/tab/mod.rs
- src/lib.rs
- tests/simple.rs
See https://github.com/atroche/rust-headless-chrome/pull/68#issue-254738053
> Make browser, tab and element modules public

- src/browser/process.rs
- src/browser/tab/mod.rs
- src/lib.rs
Pulled master and got a bunch of clippy errors, after changing this, errors went away. Feel free to ignore if this isn't needed.
edit: Was also 2 more lints left
> change clippy::stutter->module_name_repetitions

- .travis.yml
- src/browser/process.rs
- src/lib.rs
Should fix or at least shed some light on the CI failure here:
https://github.com/atroche/rust-headless-chrome/pull/84#issuecomment-468420657
> Make WS URL extraction in Process more robust

- src/browser/tab/element.rs
- src/browser/tab/mod.rs
- src/browser/transport/mod.rs
- src/browser/transport/waiting_call_registry.rs
- src/browser/transport/web_socket_connection.rs
> Add some Debug-impls

- .travis.yml
- README.md
This expands the README somewhat and hopefully makes travis check it without causing an ICE.
> Enable travis on nightly

- CHANGELOG.md
- Cargo.toml
> Add changelog, bump version to 0.1.4

- src/browser/fetcher.rs
- src/browser/mod.rs
- src/browser/process.rs
> Fix windows version of archive_name and default_executable

- src/browser/tab/element.rs
- src/protocol/runtime.rs
- tests/simple.rs
Closes #112 
Added one more field to `CallFunctionOn` struct, and argument to `call_js_fn` method
Added tests
> Added await_promise argument to call_js_fn method

- src/protocol/page.rs
I'm trying to contribute to this project, But first I need to learn git workflow so I created this simple pull request to learn.
> add childFrames field to FrameTree struct.

- src/browser/tab/element.rs
This PR adds an implicit scroll into view for elements. It is necessary to ensure a smooth flow of execution. The scroll is triggered before any action and only if the element is partially or fully out of view.
The JS code is based on Puppeteer's [implementation](https://github.com/GoogleChrome/puppeteer/blob/6860d73212d2a36fd789a9244667be574f396164/lib/JSHandle.js#L162-L186).
> Add implicit scroll into view for elements

- Cargo.toml
- tests/simple.rs
This bumps some dependencies to recent versions, tests seem to work fine.
> Bump dependencies

- Cargo.toml
- src/browser/process.rs
- src/browser/tab/mod.rs
- src/protocol/network.rs
- tests/simple.rs
Implements setUserAgentOverride, issue #140
> Implement setUserAgentOverride

- src/browser/tab/element/mod.rs
- src/browser/tab/mod.rs
- src/protocol/logs.rs
- src/protocol/mod.rs
- src/protocol/profiler.rs
- src/protocol/runtime.rs
- src/protocol/types.rs
- tests/logs.rs
- tests/logs_fixtures/basic_page_with_console_messages.html
- tests/simple.rs
And log Domain basic support
Also file log is called `logs` which I don't like because module `log` is already used.
> feat(Log): add basic support for Log domain, update Runtime types

- README.md
- src/browser/tab/mod.rs
- src/protocol/network.rs
- src/protocol/types.rs
- tests/simple.rs
Fixes https://github.com/atroche/rust-headless-chrome/issues/156
> Add tab.getCookies()

- src/browser/tab/mod.rs
> Add get_title method to tab

- CHANGELOG.md
- src/browser/tab/mod.rs
See https://github.com/atroche/rust-headless-chrome/issues/171
> Add a slow motion option to tab

- src/browser/fetcher.rs
- src/browser/mod.rs
- src/lib.rs
I finally got around to integrating this with my application and ran into a few things that weren't working correctly
> fetcher options bug fixes

- CHANGELOG.md
- src/browser/tab/element/mod.rs
- src/browser/tab/mod.rs
See https://github.com/atroche/rust-headless-chrome/issues/186.
> Add Element.find_element and Element.find_elements methods

- src/browser/mod.rs
I have an application that uses this error, do you mind making it public?
> Expose the ConnectionClosed Error

- README.md
- src/browser/tab/element/mod.rs
- src/protocol/runtime.rs
- tests/simple.rs
> Document `Element.call_js_fn`

- README.md
I add some additional comments to run the examples.
> docs improvements

- src/browser/fetcher.rs
zip crate does not supports symlinks
This result in a broken application: chromium is unable to start.
This fixes #143
> use macos unzip program to unzip chromium archive 

- examples/call_js_function_with_args.rs
- examples/query_wikipedia.rs
- examples/take_screenshot.rs
- src/browser/tab/mod.rs
- src/protocol/mod.rs
- src/protocol/page.rs
- src/protocol/runtime.rs
- tests/expose_function.rs
Implement expose_function which allows us to pass callbacks to JS side to call into rust.
> Implement exposeFunction from puppeteer

- src/browser/mod.rs
- src/browser/tab/element/mod.rs
- src/browser/tab/mod.rs
- src/browser/transport/mod.rs
- src/protocol/mod.rs
Fixes some clippy warnings.
This is still far from fixing _all_ clippy warnings, but that is all I have time for at the moment.
> fix some clippy warnings

- examples/local_storage.rs
- src/browser/tab/mod.rs
- tests/local_storage.rs
- tests/simple.html
- tests/simple.rs
> Implemented localStorage functionality

- src/browser/tab/mod.rs
- src/protocol/mod.rs
- src/protocol/network.rs
see [#146](https://github.com/atroche/rust-headless-chrome/issues/146)
> Wait for loadingFinished before requesting response body

- src/browser/tab/mod.rs
- src/protocol/input.rs
This follows puppeteers convention -https://github.com/puppeteer/puppeteer/blob/b8806d5625ca7835abbaf2e997b0bf35a5679e29/src/common/Input.ts#L239-L245
> update type_str method to use insertText API

- src/protocol/mod.rs
- src/protocol/runtime.rs
> Add Runtime.consoleAPICalled.

- src/browser/mod.rs
As new Microsoft Edge is based on Chromium.
Signed-off-by: Hollow Man <hollowman@opensuse.org>
> Add Microsoft Edge as well as developing channel Google Chrome binaries finding support

- LICENSE.md
> add MIT LICENSE.md file

- src/browser/tab/mod.rs
- tests/simple.rs
Deregistration is useful for some conditions like reusing a tab for different websites OR the needing for inspecting one specified response and disabling response handle.
I'd like to use `HashSet` to implement this. But it's not easy to make `ResponseHandler` Hashable.
> Add multiple response handlers and allow deregistration

- src/browser/transport/mod.rs
Mitigates the problem for us to print large html pages to pdf. 15 seconds is far to small as timeout. I reused the already configurable  idle_browser_timeout since it is a similar behavior: waiting for the browser to give a sign of life.
Hopefully thats correct :)
> #179 use idle browser timeout also for waiting on browser response

- src/browser/process.rs
Peviously, when the tests were run with cargo test,
which runs tests in parallel, the test:
"test_temporary_user_data_dir_is_removed_automatically"
would fail, because of the unsafe use of a global variable.
Since then I have learnt a bit more, and
using the thread_local! macro, the test is now thread-safe.
> Make temp data dir removal test thread safe

- README.md
- src/lib.rs
This pull request fixes two outdated code example. One incorrect markdown languange mark is also fixed.
> Fix outdated code examples

- src/types.rs
Thanks for a great library! I needed one small change for my use case, here it is if you want to merge it upstream. 
I'm using the library for a http microservice that accepts a html template _and_ `PrintToPdfOptions`, and generates a pdf. This needs a `Deserialize` impl to be possible, and also a `Default` impl to allow the field to be optional.
> Impl Deserialize and Default on PrintToPdfOptions

- src/browser/tab/mod.rs
https://github.com/atroche/rust-headless-chrome/issues/358#issue-1524469255
I'm not sure if this is appropriate to implement at the API level. This bypasses the fingerprints detectable by headless and automated browsers. However, there may be other fingerprints and technologies besides implementations.
I verified the implementation through a [testable site](https://intoli.com/blog/not-possible-to-block-chrome-headless/chrome-headless-test.html).
- Screen captured after visit in default tab implementation
- Screen capture after calling `tab.enable_stealth_mode`
> Implementation of Stealth Mode

- src/browser/tab/mod.rs
https://github.com/atroche/rust-headless-chrome/pull/360#discussion_r1070681425
Fixed to use the browser's userAgent
> Fix replace with real UserAgent

- README.md
- examples/call_js_function_with_args.rs
- examples/local_storage.rs
- examples/print_to_pdf.rs
- examples/query_wikipedia.rs
- examples/settings_and_event.rs
- examples/take_screenshot.rs
- src/browser/mod.rs
- src/browser/tab/element/mod.rs
- src/browser/tab/mod.rs
- src/lib.rs
- tests/coverage.rs
- tests/events_listeners.rs
- tests/expose_function.rs
- tests/file_chooser.rs
- tests/local_storage.rs
- tests/logs.rs
- tests/simple.rs
Fixes #367
@dogeatdog please see if this fixes your issue.
> Fix for `wait_for_initial_tab` bug

- src/browser/process.rs
This is useful for retry-loops
> Derive Clone for LaunchOptions

- Cargo.toml
- src/browser/fetcher.rs
> Remove Errant `?`'s

- src/browser/fetcher.rs
> Fix for #427 2.0

- Cargo.toml
- src/browser/transport/web_socket_connection.rs
> Implement Message Close for tungstenite protocol

- README.md
> docs: remove outdated fetch setting info

- src/browser/tab/mod.rs
> fix: find_element_by_xpath doesn't return Error: No element found

- src/browser/mod.rs
This PR adds a method for saving tabs that have been opened manually, the tabs are added to the right place in the list.
> Added a method for adding manually opened tabs

- src/browser/mod.rs
> don't close browser on drop if connect was used

- src/browser/tab/dialog.rs
- src/browser/tab/mod.rs
- tests/simple.rs
Implement handling the dialog.
related issue: #324
I'm not sure about the documentation & design of API.
So, If you have any suggestions, Please let me know.
> Implement handling the dialog

- src/lib.rs
I've updated the example code in lib.rs because it was deprecated(see issue #524), the one in the readme worked so i just took that one.
> The example code for the Quick Start in lib.rs has been updated.

- Cargo.toml
- json/browser_protocol.json
- json/js_protocol.json
- src/browser/context.rs
- src/browser/fetcher.rs
- src/browser/mod.rs
- src/browser/process.rs
- src/browser/tab/element/mod.rs
- src/browser/tab/mod.rs
- src/browser/transport/web_socket_connection.rs
- src/types.rs
- tests/simple.rs
Sorry for the duplicate PR, just wanted a quick resolution.
This PR contains protocol + dependency updates.
> feat(cdp): update protocol and other dependencies

- src/browser/process.rs
Now it is possible to store in HashMap/HashSet
> impl hash for LaunchOptions

- Cargo.toml
- src/browser/fetcher.rs
- src/browser/mod.rs
- src/browser/process.rs
- src/browser/tab/element/mod.rs
- src/browser/tab/mod.rs
- src/browser/transport/mod.rs
- src/browser/transport/waiting_call_registry.rs
- src/browser/transport/web_socket_connection.rs
- src/types.rs
- tests/simple.rs
- Update dependencies to latest
- Correct clippy lint suggestions
> chore: Update dependencies and fix clippy lint suggestions
